
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPEA_SUM = 18;
  public static final int WORD = 5;
  public static final int ASSIGNMENT = 12;
  public static final int THROWDOWN = 45;
  public static final int NUMERITO = 3;
  public static final int CASE = 37;
  public static final int ABRIRC = 10;
  public static final int ARRAY = 41;
  public static final int FOR = 21;
  public static final int PARENTESISC = 9;
  public static final int BRACKETC = 14;
  public static final int PARENTESISA = 8;
  public static final int BRACKETA = 13;
  public static final int NOT = 34;
  public static final int BLOCK = 26;
  public static final int IN = 35;
  public static final int LETRA = 4;
  public static final int BOOL = 20;
  public static final int COMMA = 15;
  public static final int VERDAD = 2;
  public static final int THROW = 44;
  public static final int WLE = 22;
  public static final int NUM = 28;
  public static final int MAIN = 43;
  public static final int IF = 23;
  public static final int EIF = 24;
  public static final int ID = 40;
  public static final int EOF = 0;
  public static final int OPAND = 48;
  public static final int OPOR = 47;
  public static final int NEW = 42;
  public static final int error = 1;
  public static final int CADENA = 6;
  public static final int START = 31;
  public static final int VOID = 16;
  public static final int FLECHA = 32;
  public static final int OPEA_MULT = 19;
  public static final int ELSE = 25;
  public static final int PUNTO = 36;
  public static final int LETTER = 29;
  public static final int FUNC = 30;
  public static final int DEFAULT = 38;
  public static final int OPER = 17;
  public static final int PUNTOC = 7;
  public static final int END = 27;
  public static final int REPLY = 39;
  public static final int VAR = 33;
  public static final int CATCH = 46;
  public static final int CERRARC = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VERDAD",
  "NUMERITO",
  "LETRA",
  "WORD",
  "CADENA",
  "PUNTOC",
  "PARENTESISA",
  "PARENTESISC",
  "ABRIRC",
  "CERRARC",
  "ASSIGNMENT",
  "BRACKETA",
  "BRACKETC",
  "COMMA",
  "VOID",
  "OPER",
  "OPEA_SUM",
  "OPEA_MULT",
  "BOOL",
  "FOR",
  "WLE",
  "IF",
  "EIF",
  "ELSE",
  "BLOCK",
  "END",
  "NUM",
  "LETTER",
  "FUNC",
  "START",
  "FLECHA",
  "VAR",
  "NOT",
  "IN",
  "PUNTO",
  "CASE",
  "DEFAULT",
  "REPLY",
  "ID",
  "ARRAY",
  "NEW",
  "MAIN",
  "THROW",
  "THROWDOWN",
  "CATCH",
  "OPOR",
  "OPAND"
  };
}

